### ISSUE TITLE
Please, upload module to PyPi

### ISSUE THREAD

**Issue by rembish** [jirutka/CSFD-parser#3]
``` bash
python setup.py sdist upload
```

**Comment by jirutka** [comment]
It’s already done, see https://pypi.python.org/pypi/csfd-parser/1.0.5.

**Comment by rembish** [comment]
Check uploaded file list at that URL. it's empty. If you already do sdist-upload command, check your console screen for some error reports.

**Comment by jirutka** [comment]
Agh, you’re right. I’ve just redeployed and it seems to be ok now. Thanks.
